# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates every 6 hours
  schedule: [{cron: "0 */6 * * *"}]
  # Lines below let you run this workflow manually from the Actions tab
  workflow_dispatch:
  # Run on push to main branch
  push: {branches: ["main", "master"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.GITHUB_TOKEN }}

          # Options
          user: skullxcode
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_lines: yes
          plugin_lines_history: 1
          plugin_lines_repositories: 100
          plugin_lines_sections: base
          theme: tokyonight
          output_path: metrics.svg
